version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flashcards_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: study
      POSTGRES_DB: flashcards_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
